name: bhaktiyoga_ios
description: A new Flutter project.
version: 1.0.19+19
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  admob_flutter: ^3.0.0
  audioplayers: ^3.0.1
  cached_network_image: ^3.2.1
  cloud_firestore: ^4.3.1
  cloud_functions: ^4.0.13
  device_preview: ^1.1.0
  firebase_admin: ^0.2.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_dynamic_links: ^5.0.15
  firebase_messaging: ^14.2.5
  flutter:
    sdk: flutter
  flutter_email_sender: ^5.1.0
  flutter_lints: ^2.0.1
  flutter_local_notifications: ^13.0.0
  flutter_mailer: ^2.0.0
  flutter_secure_storage: ^8.0.0
  flutter_signin_button: ^2.0.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.2.1
  get: ^4.6.5
  google_sign_in: ^6.0.1
  http: ^0.13.5
  im_animations: ^0.1.2
  intl: ^0.17.0
  just_audio: ^0.9.5
  just_audio_cache: ^0.1.1
  outline_gradient_button: ^2.0.0+1
  percent_indicator: ^4.2.3
  provider: ^6.0.5
  rename: ^2.1.1
  share_plus: ^6.3.1
  sign_in_with_apple: ^4.3.0
  volume_control: ^0.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/audio/
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/LoraRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/LoraRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/LoraRomanMedium.ttf
          weight: 500
